services:
  # db:
  # image: postgres:13
  # container_name: nb04-db
  # restart: always
  # env_file:
  # - ./.env.prod
  # volumes:
  # - db-data:/var/lib/postgresql/data
  # ports:
  # - '5432:5432'
  # healthcheck:
  # test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
  # interval: 10s
  # timeout: 5s
  # retries: 5

  backend:
    image: ghcr.io/kokooa/nb04-codiit-team3:dev
    container_name: nb04-backend
    restart: always
    command: ['sh', '-c', 'npx prisma migrate deploy && npm run start']
    env_file:
      - ./.env.prod
    ports:
      - '4000:4000'
    volumes:
      - ./uploads:/usr/src/app/uploads
    # depends_on:
    # db:
    # condition: service_healthy

  frontend:
    image: ghcr.io/kokooa/nb04-codiit-team3-frontend
    container_name: nb04-frontend
    restart: always
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://ec2-54-180-30-149.ap-northeast-2.compute.amazonaws.com/api
      - PORT=3000
    ports:
      - '3000:3000'

  web:
    image: nginx:alpine
    container_name: nb04-web
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

# volumes:
# uploads:
# db-data:
